version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo installing mocha...
      - npm install -g mocha
      - echo installing supertest...
      - npm install -g supertest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run test:unit
      - npm run test:integration
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - taskdef.json
    - appspec.yml
    - start.sh
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
